### ISSUE TITLE
Feature: Easier Visibility of Online Player Count

### ISSUE THREAD

**Issue by Kaiede** [mrrooster/minecraftbedrockconsole#3]
It'd be nice if it was possible to see the count of online users from the console tab since this is generally the default tab folks will look at when checking state of the server.

I wonder if it would make sense to move the immediate backup buttons out of the console tab and generally having some high level state reporting under the "Server status:" line, and add things like this there.

**Comment by mrrooster** [comment]
I've added a user online bar, to show how many users online vs the total allowed. 
Backup buttons moved as suggested.
I've also added details to the status bar.
