### ISSUE TITLE
Console not opening a second time after closing console until I restart

### ISSUE THREAD

**Issue by markerstef** [mrrooster/minecraftbedrockconsole#4]
I'm not sure if I'm the only one having this issue but when I turn on my computer and run the console, it opens and runs without issues. 
But if I close the console and try running it again, the console doesn't open up again until I restart the computer. I've tried everything and can't seem to figure it out. 

[EDIT]:
If I click on it like 10-15 times only then does it re-open again. It's not a huge deal, just not sure if there is something causing that or if it's the computer itself.

**Comment by mrrooster** [comment]
I've fixed a couple of little bugs that could be related to this.
