### ISSUE TITLE
Download Guide

### ISSUE THREAD

**Issue by TrainedPro** [mrrooster/minecraftbedrockconsole#6]
Hello! I'm sorry if this is not the proper way to contact you. I don't really know how to use GitHub and contact you the proper way.

The program you made is absolutely fabulous and would be really amazing but the issue is that i have absolutely no idea how to download it. All I've down in installed the ZIP from GitHub and I don't know how to get it running now.

You help would be greatly appreciated!

**Comment by StreamFroster** [comment]
Hello there, you may have accidentally downloaded the .zip source code from the repo, by navigating to the 'Releases' section, there should be a .exe file you could download individually. Hope this helps! 
![image](https://user-images.githubusercontent.com/56343624/158201614-e415ae76-a6f7-4ab7-8497-4c515a99e883.png)
