### ISSUE TITLE
Server Not Backing Up

### ISSUE THREAD

**Issue by TrainedPro** [mrrooster/minecraftbedrockconsole#7]
Issue:

Everytime i press backup, the server says that it backs up but it fails to create a ZIP file even though i backed up normally (Not with the ZIP option). I do not know why this issue is.

I can back up perfectly when i do it manually, even when the server is running but it doesn't do it with this program.

![Screenshot 2022-03-14 204848](https://user-images.githubusercontent.com/90309454/158209709-155ef227-2784-47b5-b543-4ffa6c183653.jpg)

**Comment by mrrooster** [comment]
This was due to later servers adding the timestamp to the server output, confusing the backup routine.

There was an additional issue where if a `whitelist.json` file was missing the backup would fail.

Both these issues have been fixed in versions greater than 202411160000,
